name: TRIGGER TESTS

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  test:
    if: startsWith(github.head_ref, 'release/v') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "hello world"

      - run: echo ${{ github.head_ref }}
      - run: echo ${{ github.repository }}
      - run: echo ${{ github.base_ref }}
      - run: echo ${{ github.event.pull_request.base.ref }}
